;(function SiteSnapshotterBootstrap(global) {
  "use strict";

  global.SiteSnapshotterBootstrap = {
    loadOrder: [
      "core/config.js",
      "core/exporter.js",
      "modules/page.js",
      "modules/dom.js",
      "modules/forms.js",
      "modules/css.js",
      "modules/jsenv.js",
      "modules/storage.js",
      "modules/network.js",
      "modules/assets.js",
      "modules/routes.js",
      "modules/auth.js",
      "modules/frameworks.js",
      "modules/security.js",
      "modules/entities.js",
      "modules/performance.js",
      "modules/timeline.js",
      "modules/telemetry.js",
      "modules/schemas.js",
      "modules/runtime_state.js",
      "modules/feature_flags.js",
      "modules/module_graph.js",
      "modules/scenario.js",
      "modules/source_maps.js",
      "modules/intelligence.js",
      "modules/endpoints.js",
      "modules/state_map.js",
      "modules/tech_tree.js",
      "modules/confidence.js",
      "modules/evidence.js",
      "injector.js"
    ],
    packageFiles: [
      "page.json",
      "dom.json",
      "forms.json",
      "css.json",
      "jsenv.json",
      "storage.json",
      "network.json",
      "assets.json",
      "routes.json",
      "auth.json",
      "framework.json",
      "security.json",
      "entities.json",
      "performance.json",
      "analysis.json",
      "timeline.json",
      "telemetry.json",
      "schemas.json",
      "runtime_state.json",
      "feature_flags.json",
      "module_graph.json",
      "scenario.json",
      "source_maps.json",
      "intelligence.json",
      "endpoints.json",
      "state_map.json",
      "tech_tree.json",
      "confidence.json",
      "evidence.json",
      "screenshot_meta.json"
    ],
    note: "injector.js специально самодостаточный для вставки в DevTools Console; module-файлы фиксируют зоны ответственности capture pipeline."
  };
})(window);
